config/routes.rb
Rails.application.routes.draw do


  root to: 'pages#home'

  get '/kitchens' => 'pages#kitchens'

  get '/bathrooms' => 'pages#bathrooms'

  get '/new_builds' => 'pages#new_builds'

  get '/extensions' => 'pages#extensions'

  get '/externals' => 'pages#externals'

  get '/contact_us' => 'pages#contact_us'

  get '/all_services' => 'pages#all_services'

  get '/gallery' => 'pages#gallery'


  match '/contacts',     to: 'contacts#new',             via: 'get'
resources "contacts", only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:notice] = 'Thank you for your message. We will contact you soon!'
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def kitchens
  end

  def bathrooms
  end

  def new_builds
  end

  def extensions
  end

  def externals
  end

  def contact_us
  end

  def all_services
  end

  def gallery
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/create.html.erb
<div>
  <% flash.each do |key, value| %>
    <div>
      <a href="#" data-dismiss="alert">×</a>
        <%= value %>
    </div>
  <% end %>
</div>

app/views/contacts/new.html.erb
<div align="center">
  <h3>Send A message to Us</h3>

  <%= simple_form_for @contact, :html => {:class => 'form-horizontal' } do |f| %>
    <%= f.input :name, :required => true %>
    <%= f.input :email, :required => true %>
    <%= f.input :message, :as => :text, :required => true %>
    <div class= "hidden">
      <%= f.input :nickname, :hint => 'Leave this field blank!' %>
    </div>
    <div>
      </br>
      <%= f.button :submit, 'Send message', :class=> "btn btn-primary" %>
    </div>
  <% end %>
</div>


<div align="center">
<h2>Contact Us</h2>
<h3>Address</h3>
<h4>
13 Hazlemere Road,
Penn,
HP10 8AD.

</h4>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Dulieu Builders</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>

    <%= render 'shared/navbar' %>

    <main class="Site-content" style="padding-top: 50px;">
      <%= yield %>
    </main>
    <%= render 'shared/footer' %>

    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/pages/bathrooms.html.erb
<div class="container">
  <div align="center" class="padded-top">
    <h1>Bathrooms</h1>
    <h4>
    Dulieu Builders can help in designing and bringing to you the bathroom that best suits you. With our knowledge and experience we will deliver a high quality product whatever the size of your project.
    </h4>
  </div>
</div>

<div class="container text-center padded">
    <div class="row services">
      <%= image_tag("bathrooms.JPG") %>
  </div>
</div>

app/views/pages/contact.html.erb
Name

app/views/pages/contact_us.html.erb
<div class="padded">
  <div align="center">
   <div class="underline">
   <h2>Contact Us</h2>
   </div>
    <h3>Email</h3>
    <h4>
      <a href="mailto:joe@dulieubuilders.com">joe@dulieubuilders.com</a>
    </h4>

    <h3>Phone</h3>
    <h4>
      <a href="tel:07813052915">07813052915</a>
    </h4>
    <h3>Address</h3>
    <h4>
      14 Hazlemere Road,
      Penn,
      HP10 8AD.
    </h4>

  </div>
</div>

app/views/pages/extensions.html.erb
<div class="container">
  <div align="center" class="padded-top">
    <h1>Extensions</h1>
    <h4>
    With over 40 years experience in the Buckinghamshire area Dulieu Builders deliver consultation and completion on extensions both big and small. With our knowledge we can aid clients with expert advice in how to make the most out of your project.
    </h4>
  </div>
</div>

<div class="container text-center padded">
    <div class="row services">
      <%= image_tag("extensions.jpg") %>
  </div>
</div>

app/views/pages/externals.html.erb
<div class="container">
  <div align="center" class="padded-top">
    <h1>Externals</h1>
    <h4>
    Dulieu Builders deliver high quality external and landscaping services to our clients. Making the most out of the land you have to frame your property in both a charming and practical manner
    </h4>
  </div>
</div>

<div class="container text-center padded">
    <div class="row services">
      <%= image_tag("externals.JPG") %>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(44, 52, 47, 0.6) 0%, rgba(15, 36, 71, 0.7) 50%), url('<%= image_path('home.jpg') %>');">
</div>




<div class="container text-center padded">
          <div class="row">
            <div class="about">
                <div class="col-xs-12 col-sm-4 ">
                  <a href="new_builds"><%= image_tag("new_build.png")%></a>
                    <p>New Builds</p>
                </div>
                 <div class="col-xs-12 col-sm-4 ">
                  <a href="kitchens"><%= image_tag("kitchen.png")%></a>
                    <p>Kitchens</p>
                </div>
                <div class="col-xs-12 col-sm-4 ">
                  <a href="bathrooms"><%= image_tag("bathroom.png")%></a>
                    <p>Bathrooms</p>
                </div>
                 <div class="col-xs-12 col-sm-4 ">
                  <a href="extensions"><%= image_tag("extension.png")%></a>
                    <p>Extensions</p>
                </div>
                <div class="col-xs-12 col-sm-4 ">
                  <a href="externals"><%= image_tag("external.png")%></a>
                    <p>External</p>
                </div>
                 <div class="col-xs-12 col-sm-4 ">
                  <a href="contact_us"><%= image_tag("contact_us.png")%></a>
                    <p>Contact Us</p>
                </div>
</div>
</div>
</div>

app/views/pages/kitchens.html.erb
<div class="container">
  <div align="center" class="padded-top">
    <h1>Kitchens</h1>
    <h4>
    Dulieu Builders can help to both design and advise on what kitchen best suits you. Seeing the process from start to finish with the promise of delivering a comprehensive finished product that lives up to the needs of those using the space.
    </h4>
  </div>
</div>

<div class="container text-center padded">
    <div class="row services">
      <%= image_tag("kitchens.JPG") %>
  </div>
</div>

app/views/pages/new_builds.html.erb
<div class="container">
  <div align="center" class="padded-top">
    <h1>New Builds</h1>
    <h4>Dulieu Builders have experience in delivering new build homes of various sizes. Dealing with architects and other contractors to complete all projects both to budget and on time, always completed with high quality.
    </h4>
  </div>
</div>

<div class="container text-center padded">
    <div class="row services">
      <%= image_tag("home.jpg") %>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="navbar navbar-fixed-bottom footer-size" role="navigation">
  <div id="footer">
    <div class="container">
      <div class="row">
        <div class="col-xs-4 small-padded footer-icon">
          <ul class="list-inline">
            <li><a href="https://www.linkedin.com/in/joe-dulieu-02991599/"><i class="fa fa-linkedin"></i></a></li>
            <li><a href="https://www.facebook.com/pages/Dulieu-Builders/441865132491991"><i class="fa fa-facebook"></i></a></li>
            <li><a href="tel:07813052915"><i class="fa fa-phone"></i></a></li>
        </div>
        <div class="col-xs-8 text-right">
          <h4>Dulieu Builders</h4>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-wagon-fixed">
  <!-- Logo -->
  <%= link_to root_path, class: "nav-logo" do %>
 <%= image_tag "dulieu-builders-logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <%= link_to root_path do %>
      <p class="navbar-wagon-item navbar-wagon-link">Home</p>
    <% end %>


  <div class="dropdown">
            <p href="#" data-toggle="dropdown" class="navbar-wagon-item navbar-wagon-link dropdown-toggle">Services <b class="caret"></b></p>
            <ul class="dropdown-menu">
                <li><a href="new_builds">New Builds</a></li>
                <li><a href="kitchens">Kitchens</a></li>
                <li><a href="bathrooms">Bathrooms</a></li>
                <li><a href="extensions">Extensions</a></li>
                <li><a href="externals">External</a></li>
            </ul>
        </div>

    <%= link_to contact_us_path do %>
      <p class="navbar-wagon-item navbar-wagon-link">Contact Us</p>
    <% end %>









    <!-- Search form -->
    <!-- <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form>
 -->
    <!-- Different navigation if login or not -->


      <!-- Notification -->


      <!-- Profile picture and dropdown -->




      <!-- Login text link -->



    <!-- Button (call-to-action) -->

  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">

        <li>

              <%= link_to root_path do %>
                <%= t(".home", default: "Home") %>
              <% end %>
              </li>
              <li>
              <%= link_to contact_us_path do %>
      <%= t(".contact_us", default: "Contact Us") %>
    <% end %>
    </li>

      </ul>
    </div>
  </div>
</div>